COMPONENT_ADD_INCLUDEDIRS=mongoose/
COMPONENT_SRCDIRS=mongoose/

ALL_FLAGS += -DMG_ENABLE_FILESYSTEM
ALL_FLAGS += -DESP_PLATFORM
#ALL_FLAGS += -DMG_ENABLE_SSL=1
ALL_FLAGS += -DMG_ENABLE_IPV6=1
ALL_FLAGS += -DMG_ENABLE_HTTP_SSI=1
ALL_FLAGS += -DMG_ENABLE_BROADCAST=1
#ALL_FLAGS += -DMG_SSL_IF=MG_SSL_IF_MBEDTLS



CFLAGS += ${ALL_FLAGS}

CXXFLAGS += ${ALL_FLAGS}
