COMPONENT_ADD_INCLUDEDIRS=mongoose/
COMPONENT_SRCDIRS=mongoose/

ALL_FLAGS += -DMG_ENABLE_FILESYSTEM
ALL_FLAGS += -DESP_PLATFORM
ALL_FLAGS += -DMG_LWIP=1
ALL_FLAGS += -DMG_DISABLE_DIRECTORY_LISTING=1
ALL_FLAGS += -DMG_DISABLE_DAV=1
ALL_FLAGS += -DMG_DISABLE_CGI=1



CFLAGS += ${ALL_FLAGS}

CXXFLAGS += ${ALL_FLAGS}
