COMPONENT_ADD_INCLUDEDIRS=mongoose/
COMPONENT_SRCDIRS=mongoose/
COMPONENT_SRCDIRS+=./

ALL_FLAGS+=-Dmbedtls_time_t=time_t
ALL_FLAGS+=-DMG_SSL_CRYPTO_MODERN

CFLAGS += ${ALL_FLAGS}

CXXFLAGS += ${ALL_FLAGS}
