COMPONENT_ADD_INCLUDEDIRS=spiffs/src
COMPONENT_SRCDIRS=spiffs/src
COMPONENT_PRIV_INCLUDEDIRS=spiffs/src
COMPONENT_PRIV_INCLUDEDIRS+=spiffs/src/default
COMPONENT_PRIV_INCLUDEDIRS+=spiffs/src/test
CFLAGS	+= -DCONFIG_BUILD_SPIFFS
